export declare const commonSheets: {
    gtrow: (v: any) => string;
    gtcol: (v: any) => string;
    grow: (v: any) => string;
    gcol: (v: any) => string;
    items: (v: any) => string;
    justify: (v: any) => string;
    'align-self': (v: any) => string;
    'align-content': (v: any) => string;
    p: (v: any) => string;
    px: (v: any) => string;
    py: (v: any) => string;
    pl: (v: any) => string;
    pt: (v: any) => string;
    pr: (v: any) => string;
    pb: (v: any) => string;
    m: (v: any) => string;
    mx: (v: any) => string;
    my: (v: any) => string;
    ml: (v: any) => string;
    mt: (v: any) => string;
    mr: (v: any) => string;
    mb: (v: any) => string;
    w: (v: any) => string;
    'w-min': (v: any) => string;
    'w-max': (v: any) => string;
    'w-min-max': (v: any) => string;
    h: (v: any) => string;
    'h-min': (v: any) => string;
    'h-max': (v: any) => string;
    'h-min-max': (v: any) => string;
    wh: (v: any) => string;
    'wh-min': (v: any) => string;
    'wh-max': (v: any) => string;
    b: (v: any) => string;
    bl: (v: any) => string;
    bt: (v: any) => string;
    br: (v: any) => string;
    bb: (v: any) => string;
    bc: (v: any) => string;
    radius: (v: any) => string;
    bg: (v: any) => string;
    bgc: (v: any) => string;
    gradient: (v: any) => string;
    linear: (v: any) => string;
    ease: (v: any) => string;
    'ease-in': (v: any) => string;
    'ease-out': (v: any) => string;
    'ease-in-out': (v: any) => string;
    'move-x': (v: any) => string;
    'move-y': (v: any) => string;
    'move-z': (v: any) => string;
    shadow: (v: any) => any;
    rotate: (v: any) => string;
    scale: (v: any) => string;
    scroll: string;
    center: string;
    full: string;
    row: string;
    'row-reverse': string;
    col: string;
    'col-reverse': string;
    'pe-none': string;
    'pe-auto': string;
};
