declare const commonSheets: {
    gradient: (v: any) => string;
    backdrop: (v: string) => string;
    row: string;
    col: string;
    "row-r": string;
    "col-r": string;
    "center-start": string;
    "center-center": string;
    "center-end": string;
    "start-start": string;
    "start-center": string;
    "start-end": string;
    "end-start": string;
    "end-center": string;
    "end-end": string;
    "between-start": string;
    "between-center": string;
    "between-end": string;
    "around-start": string;
    "around-center": string;
    "around-end": string;
    "snap-x": string;
    "snap-y": string;
    "snap-center;": string;
    serif: string;
};
export default commonSheets;
