export declare const commonSheets: {
    dis: (v: any) => string;
    items: (v: any) => string;
    justify: (v: any) => string;
    self: (v: any) => string;
    content: (v: any) => string;
    z: (v: any) => string;
    p: (v: any) => string;
    px: (v: any) => string;
    py: (v: any) => string;
    pl: (v: any) => string;
    pt: (v: any) => string;
    pr: (v: any) => string;
    pb: (v: any) => string;
    m: (v: any) => string;
    mx: (v: any) => string;
    my: (v: any) => string;
    ml: (v: any) => string;
    mt: (v: any) => string;
    mr: (v: any) => string;
    mb: (v: any) => string;
    w: (v: any) => string;
    minw: (v: any) => string;
    maxw: (v: any) => string;
    mmw: (v: any) => string;
    h: (v: any) => string;
    minh: (v: any) => string;
    maxh: (v: any) => string;
    mmh: (v: any) => string;
    b: (v: any) => string;
    bt: (v: any) => string;
    br: (v: any) => string;
    bb: (v: any) => string;
    bl: (v: any) => string;
    "b-color": (v: any) => string;
    "b-style": (v: any) => string;
    radius: (v: any) => string;
    "radius-t-l": (v: any) => string;
    "radius-t-r": (v: any) => string;
    "radius-b-l": (v: any) => string;
    "radius-b-r": (v: any) => string;
    font: (v: any) => string;
    bg: (v: any) => string;
    bgc: (v: any) => string;
    "ease-in": (v: any) => string;
    "ease-in-out": (v: any) => string;
    scale: (v: any) => string;
    center: string;
    full: string;
    row: string;
    "row-reverse": string;
    col: string;
    "col-reverse": string;
    fixed: string;
    static: string;
    absolute: string;
    relative: string;
    sticky: string;
    left: string;
    top: string;
    right: string;
    bottom: string;
};
